### ISSUE TITLE
Could not find 'has_ards_disease' column anywhere.

### ISSUE THREAD

**Issue by xinformatics** [Qianxiaoxie917/ARDS-definitions#2]
Hi @Qianxiaoxie917 , thank you for the code. I am trying to extract the data from MIMIC4 using the ARDS criteria as you have mentioned. 

I could not find 'has_ards_disease' column anywhere. This column has been used in "MIMICIV_ARDS_whole_subset.Rmd" Line 91

`(pat_MIMICIV_ARDS_subset <- pat_MIMICIV_ARDS_subset[!is.na(pat_MIMICIV_ARDS_subset$has_ards_disease) | !is.na(pat_MIMICIV_ARDS_subset$has_heart_failure_disease), ]`
)

to subset patients.  I double checked but it does not show on BigQuery too. Could you please tell me if you renamed the column name?

There is one column name "has_pneumonia_disease" in ards_icd.sql with J80 ICD10 code which is for ARDS. Are these two same?

Thank you

**Comment by Qianxiaoxie917** [comment]
Hi. Thanks for your comment. I apologize for the confusion. You are correct that "has_pneumonia_disease" should be changed to "has_ards_disease". I have updated the code accordingly.

**Comment by xinformatics** [comment]
Thank you.
